apiVersion: v2
name: payerfsp
version: 1.0.0
description: A Helm chart for Kubernetes
appVersion: "ml-testing-toolkit: v17.0.0, ml-testing-toolkit-ui: v15.4.0, sdk-scheme-adapter: v23.1.1"
home: http://mojaloop.io
icon: http://mojaloop.io/images/logo.png
sources:
  - https://github.com/mojaloop/mojaloop
  - https://github.com/mojaloop/helm
  - https://github.com/mojaloop/sdk-scheme-adapter
maintainers:
  - name: Vijay Kumar Guthi
    email: vijaya.guthi@infitx.com
dependencies:
  - name: sdk-scheme-adapter
    repository: http://mojaloop.io/helm/repo
    tags:
      - sdk-scheme-adapter
    version: 1.2.0
    condition: sdk-scheme-adapter.enabled
  - name: ml-testing-toolkit
    repository: http://mojaloop.io/helm/repo
    tags:
      - testing-toolkit
    version: 17.0.0
    condition: ml-testing-toolkit.enabled
  - name: common
    repository: "https://mojaloop.github.io/charts/repo"
    tags:
      - moja-common
    version: 2.0.0
