# This is a YAML-formatted file.

## Local re-usable configs
config:
  payerName: &CONFIG_PAYER_NAME fxpayerdfsp
  payeeName: &CONFIG_PAYEE_NAME fxpayeedfsp
  fxpName: &CONFIG_FXP_NAME testfxp1
  payerServiceName: &CONFIG_PAYER_SERVICE_NAME fxpayerdfsp
  payeeServiceName: &CONFIG_PAYEE_SERVICE_NAME fxpayeedfsp
  fxpServiceName: &CONFIG_FXP_SERVICE_NAME fxp
  endpointALS: &ENDPOINT_ALS 'moja-account-lookup-service'
  endpointQuotes: &ENDPOINT_QUOTES 'moja-quoting-service'
  endpointTransfers: &ENDPOINT_TRANSFERS 'moja-ml-api-adapter-service'
  redisHost: &REDIS_HOST 'fx-redis-master'
  redisPort: &REDIS_PORT 6379
  mojaloopConnectorImageTag: &MOJALOOP_CONNECTOR_IMAGE_TAG v23.2.0-snapshot.2

redis:
  enabled: true

  replica:
    replicaCount: 1

  ## @param architecture Redis&reg; architecture. Allowed values: `standalone` or `replication`
  ##
  architecture: standalone

  ## Redis&reg; Authentication parameters
  ## ref: https://github.com/bitnami/containers/tree/main/bitnami/redis#setting-the-server-password-on-first-run
  ##
  auth:
    ## @param auth.enabled Enable password authentication
    ##
    enabled: false

  ## @section Persistence parameters
  ##
  master:
    ## Enable persistence using Persistent Volume Claims
    ## ref: https://kubernetes.io/docs/user-guide/persistent-volumes/
    persistence:
      ## @param master.persistence.enabled Enable persistence on Redis&reg; master nodes using Persistent Volume Claims
      ##
      enabled: false

fxpayerdfsp:
  enabled: true

  config:
    simName: *CONFIG_PAYER_SERVICE_NAME
    database: &CONFIG_PAYER_DB 1

  sdk-scheme-adapter:
    sdk-scheme-adapter-api-svc:
      image:
        tag: *MOJALOOP_CONNECTOR_IMAGE_TAG
      redis:
        database: *CONFIG_PAYER_DB
        host: *REDIS_HOST
        port: *REDIS_PORT

      config:
        simName: *CONFIG_PAYER_SERVICE_NAME
      
      env:
        DFSP_ID: *CONFIG_PAYER_NAME
        BACKEND_ENDPOINT: '{{ .Release.Name }}-{{ .Values.config.simName }}-ttk-backend:4040'
        GET_SERVICES_FXP_RESPONSE: *CONFIG_FXP_SERVICE_NAME
        ALS_ENDPOINT: *ENDPOINT_ALS
        QUOTES_ENDPOINT: *ENDPOINT_QUOTES
        TRANSFERS_ENDPOINT: *ENDPOINT_TRANSFERS
        FX_QUOTES_ENDPOINT: '{{ .Release.Name }}-fxp-sdk-api-svc:4000'
        FX_TRANSFERS_ENDPOINT: *ENDPOINT_TRANSFERS

  ml-testing-toolkit:
    enabled: true

    ml-testing-toolkit-backend:
      ingress:
        enabled: true
        hosts:
          specApi:
            host: 'ttk-specapi.fxpayerdfsp.local'
          adminApi:
            host: 'ttk.fxpayerdfsp.local'

    ml-testing-toolkit-frontend:
      ingress:
        enabled: true
        hosts:
          ui:
            host: ttk.fxpayerdfsp.local

      config:
        API_BASE_URL: 'http://ttk.fxpayerdfsp.local'

fxpayeedfsp:
  enabled: true

  ## Local re-usable configs
  config:
    simName: *CONFIG_PAYEE_SERVICE_NAME
    database: &CONFIG_PAYEE_DB 2

  sdk-scheme-adapter:
    sdk-scheme-adapter-api-svc:
      image:
        tag: *MOJALOOP_CONNECTOR_IMAGE_TAG

      redis:
        database: *CONFIG_PAYEE_DB
        host: *REDIS_HOST
        port: *REDIS_PORT

      config:
        simName: *CONFIG_PAYEE_SERVICE_NAME

      env:
        DFSP_ID: *CONFIG_PAYEE_NAME
        BACKEND_ENDPOINT: '{{ .Release.Name }}-{{ .Values.config.simName }}-ttk-backend:4040'
        SUPPORTED_CURRENCIES: TZS
        ALS_ENDPOINT: *ENDPOINT_ALS
        QUOTES_ENDPOINT: *ENDPOINT_QUOTES
        TRANSFERS_ENDPOINT: *ENDPOINT_TRANSFERS

  ml-testing-toolkit:
    enabled: true

    ml-testing-toolkit-backend:
      ingress:
        enabled: true
        hosts:
          specApi:
            host: 'ttk-specapi.fxpayeedfsp.local'
          adminApi:
            host: 'ttk.fxpayeedfsp.local'

    ml-testing-toolkit-frontend:
      ingress:
        enabled: true
        hosts:
          ui:
            host: 'ttk.fxpayeedfsp.local'

      config:
        API_BASE_URL: 'http://ttk.fxpayeedfsp.local'

fxp:
  enabled: true

  ## Local re-usable configs
  config:
    simName: *CONFIG_FXP_SERVICE_NAME
    database: &CONFIG_FXP_DB 5

  sdk-scheme-adapter:
    sdk-scheme-adapter-api-svc:
      image:
        tag: *MOJALOOP_CONNECTOR_IMAGE_TAG

      redis:
        database: *CONFIG_FXP_DB
        host: *REDIS_HOST
        port: *REDIS_PORT

      config:
        simName: *CONFIG_FXP_SERVICE_NAME

      env:
        DFSP_ID: *CONFIG_FXP_NAME
        BACKEND_ENDPOINT: '{{ .Release.Name }}-{{ .Values.config.simName }}-ttk-backend:4040'
        FX_QUOTES_ENDPOINT: '{{ .Release.Name }}-fxpayerdfsp-sdk-api-svc:4000'
        FX_TRANSFERS_ENDPOINT: *ENDPOINT_TRANSFERS

  ml-testing-toolkit:
    enabled: true

    ml-testing-toolkit-backend:
      ingress:
        enabled: true
        hosts:
          specApi:
            host: 'ttk-specapi.fxp.local'
          adminApi:
            host: 'ttk.fxp.local'

    ml-testing-toolkit-frontend:
      ingress:
        enabled: true
        hosts:
          ui:
            host: 'ttk.fxp.local'

      config:
        API_BASE_URL: 'http://ttk.fxp.local'
